### ISSUE TITLE
Goody Suggesitons

### ISSUE THREAD

**Issue by JREAM** [dansackett/dotfiles#1]
### CLI Utils (NPM)
- https://www.npmjs.com/package/vtop  <-- Hotness
- https://www.npmjs.com/package/fkill-cli  <-- Time Saver!
- https://github.com/localtunnel/localtunnel  <-- Like ngrok, still prefer ngrok2 myself though im grandfathered in ngrok for custom vhost (paid now)

### CLI Utils (Bash)
- https://github.com/shyiko/commacd  <-- Pretty neat

### Python: PipEnv
- https://github.com/kennethreitz/pipenv  <-- Mad popular overtaking venv

### Version Manage Node
- _Probably familiar with already, Love it_
- https://github.com/creationix/nvm
    - `nvm install 8.9.1` (LTS)
    - `nvm alias default 8.9.1`
    - `npm i -g <global-packages, prefer using an *.sh for this>` [example](https://github.com/JREAM/dotfiles/blob/master/nvm-update.sh)
   - Also, you can create a `.node-version` file with content: `7.5.0`, this will autoload version for that CWD.

Also, once again love the organization of files you have!

**Comment by dansackett** [comment]
Cool suggestions! I could see some of the CLI utils being nice I'm just so set in my workflow that I rarely look for different ways to do things. I did start using tmux locally a few months ago and love that though.

`pipenv` has a lot of new cool features too but I don't think I'm ready to ditch `virtualenv-wrapper` quite yet.

**Comment by JREAM** [comment]
I think PipEnv does seem really convenient, its just like venv-wrapper with what you setup. I haven't played with it a whole lot, but it seems pretty cool, havent dug deep into it but just playing with it is not oo shabby. I like the output color CLI and its easy to use if you havent tried it yet.

Tmux is cool, I havent made much use with it but on SSH its amazing (Saw a guy using it, hardcore time saver)

```
pip install pipenv
pip3 install pipenv  # if you do this too, lol
mkdir anything
pipenv --python 3.6
```
- Creates Venv Random Name: `Virtualenv location: /home/jesse/.local/share/virtualenvs/bnotes-voM752NZ`
- Creates `Pipfile` with:
```[[source]]                                           

name = "pypi"
url = "https://pypi.python.org/simple"
verify_ssl = true


[packages]



[requires]

python_version = "3.6"


[dev-packages]

```

**Comment by JREAM** [comment]
Try ZSH + Oh My ZSH, then enable some plugs here https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins -- add your own theme if you want, you might faint like I did, I cant even explain the amazement
